#
#  BedFallback, a Minecraft mod that stores last bed spawn positions
#  Copyright (C) 2025 legenden (MagnusHJensen)
#
#  This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.2.0
group=dk.magnusjensen.bedfallback
java_version=17

# Common
minecraft_version=1.20.1
mod_name=BedFallback
mod_author=legenden (MagnusHJensen)
mod_id=bedfallback
license=LGPL-3.0
credits=
description=If your bed is broken, your spawn point is your previous bed
homepage=https://curseforge.com/minecraft/mc-mods/bedfallback
github=https://github.com/magnushjensen/bed-fallback
minecraft_version_range=[1.20.1, 1.21)
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Fabric
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.16.9

# Forge
forge_version=47.2.30
forge_loader_version_range=[47,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
