#
#  BedFallback, a Minecraft mod that stores last bed spawn positions
#  Copyright (C) 2025 legenden (MagnusHJensen)
#
#  This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.3.0
group=dk.magnusjensen.bedfallback
java_version=25

# Common
minecraft_version=26.2
mod_name=BedFallback
mod_author=legenden (MagnusHJensen)
mod_id=bedfallback
license=LGPL-3.0
credits=
description=If your bed is broken, your spawn point is your previous bed
homepage=https://curseforge.com/minecraft/mc-mods/bedfallback
github=https://github.com/magnushjensen/bed-fallback
minecraft_version_range=[26.2, 26.3)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-2

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.159.0+26.2
fabric_loader_version=0.19.5

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.2.0.76
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
